import {
  Banknote,
  Wallet,
  Percent,
  TrendingUp,
  Sparkles,
  Gift,
  Briefcase,
  PiggyBank,
  Coins,
  UtensilsCrossed,
  Coffee,
  Car,
  Bus,
  Fuel,
  Home,
  Plug,
  Wifi,
  Smile,
  Dumbbell,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  HeartPulse,
  Pill,
  Stethoscope,
  Plane,
  GraduationCap,
  Baby,
  PawPrint,
  Gamepad2,
  Film,
  Music,
  Repeat,
  CreditCard,
  Receipt,
  Landmark,
  Smartphone,
  Tag,
  type LucideIcon,
} from 'lucide-react';

// Registry of every icon a category may reference by name. New custom categories
// can pick from PICKABLE_ICONS; unknown names fall back to a neutral Tag.
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Banknote,
  Wallet,
  Percent,
  TrendingUp,
  Sparkles,
  Gift,
  Briefcase,
  PiggyBank,
  Coins,
  UtensilsCrossed,
  Coffee,
  Car,
  Bus,
  Fuel,
  Home,
  Plug,
  Wifi,
  Smile,
  Dumbbell,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  HeartPulse,
  Pill,
  Stethoscope,
  Plane,
  GraduationCap,
  Baby,
  PawPrint,
  Gamepad2,
  Film,
  Music,
  Repeat,
  CreditCard,
  Receipt,
  Landmark,
  Smartphone,
  Tag,
};

export const PICKABLE_ICONS: string[] = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? Tag;
}
